### ISSUE TITLE
avro_schema.export(handle) must not change type schema for nullable fields

### ISSUE THREAD

**Issue by opomuc** [tarantool/avro-schema#38]
We define following schema

```
schema = json.decode([[
     {"name": "foo", "type": "record", "fields": [{"name": "bar", "type": "long*"}]}
]])
ok, handle = avro.create(schema)
```
After export nullable field's type will be replaced with a table `{ type, nullable }`
```
avro.export(handle)
---
- type: record
  fields:
  - type:
      type: long
      nullable: true
    name: bar
  name: foo
...
```
This behavior is unobvious and follows internal representation which is unsuitable for external API.

It should return `type: long*`
